"""Add candidate_position to Booking model

Revision ID: 01c44a652d92
Revises: 2a78d1eed0be
Create Date: 2025-03-17 18:19:19.704086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c44a652d92'
down_revision = '2a78d1eed0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('candidate_position', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'candidate_position')
    # ### end Alembic commands ###
