"""Add Zoom integration fields to Recruiter

Revision ID: 257b6d83bda3
Revises: 5b9b6f9dcf30
Create Date: 2025-03-16 15:13:22.995262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257b6d83bda3'
down_revision = '5b9b6f9dcf30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiter', sa.Column('zoom_access_token', sa.String(length=500), nullable=True))
    op.add_column('recruiter', sa.Column('zoom_refresh_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiter', 'zoom_refresh_token')
    op.drop_column('recruiter', 'zoom_access_token')
    # ### end Alembic commands ###
