"""Add Invitation model and cancel_count

Revision ID: 2a78d1eed0be
Revises: 8a557f469d99
Create Date: 2025-03-17 17:34:11.147680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a78d1eed0be'
down_revision = '8a557f469d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('cancel_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation', 'cancel_count')
    # ### end Alembic commands ###
