"""Update Recruiter model with timezone and add meeting_link to Booking

Revision ID: 5b9b6f9dcf30
Revises: 3c2bba4d0425
Create Date: 2025-03-15 21:50:33.087975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9b6f9dcf30'
down_revision = '3c2bba4d0425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('meeting_link', sa.String(length=200), nullable=True))
    op.add_column('recruiter', sa.Column('timezone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiter', 'timezone')
    op.drop_column('booking', 'meeting_link')
    # ### end Alembic commands ###
